[package]
name = "iot_hub"
version = "0.1.0"
authors = ["yelcat <yelcat@gmail.com>"]

[dependencies]
log = "0.3.8"
env_logger = "0.4.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1.17"
tokio-core = "0.1.11"
